with open('smart_search_router.py', 'r', encoding='utf-8') as f: code = f.read()
code = code.replace('raw.get(\"floor_words\", [])', 'raw.get(\"floor_words\") or []')
code = code.replace('raw.get(\"floor_numbers\", [])', 'raw.get(\"floor_numbers\") or []')
code = code.replace('raw.get(\"nearby_locations\", [])', 'raw.get(\"nearby_locations\") or []')
code = code.replace('raw.get(\"main_features\", [])', 'raw.get(\"main_features\") or []')
code = code.replace('raw.get(\"extra_features\", [])', 'raw.get(\"extra_features\") or []')
code = code.replace('raw.get(\"features\", [])', 'raw.get(\"features\") or []')
code = code.replace('raw.get(\"locations\", [])', 'raw.get(\"locations\") or []')
with open('smart_search_router.py', 'w', encoding='utf-8') as f: f.write(code)
